#!/usr/bin/env bash
# Run the OA4MP CLI (command line interface). This will allow you to edit, create or remove
# clients, approvals. It will also allow you to copy one store to another completely.
# Invoke with --help for more information.
#
# The next 5 entries completely determine how this operates. Change these to whatever you want if
# different from the standard install.

OA4MP_ROOT=${OA4MP_HOME}
DEFAULT_CONFIG=$OA4MP_ROOT/etc/cfg.xml
DEFAULT_TARGET=default
DEFAULT_ENV=$OA4MP_ROOT/etc/cli.properties
cliJar=$OA4MP_ROOT/lib/cli.jar
logFile=$OA4MP_ROOT/var/log/cli.log

# End of user serviceable parts.

if [[  "$1" = "--help" || $# -gt 2 ]];then
  echo "cli [configName configFile environment"]
  echo "Start the OAuth 2 forMyProxy command line admin tool with the"
  echo "given configuration name in the given configuration file (full path)."
  echo "No arguments means to use the config named '$DEFAULT_TARGET' in the file  '$DEFAULT_CONFIG'"
  echo "and the default properties file at '$DEFAULT_ENV'"
  echo "One argument is assumed to be the configuration name in the default config file."
  exit 1
fi

target=${1:-$DEFAULT_TARGET}
adminCfg=${2:-$DEFAULT_CONFIG}
env=${3:-$DEFAULT_ENV}

java -jar $cliJar   -cfg $adminCfg -name $target -log $logFile -set_env $env -v

if [ $? != 0 ]; then
  exit 1
fi

exit 0
