#!/usr/bin/env bash
# Run the OA4MP JWT (JSON web token) utility.
# Invoke with --help for more information.
#
# The next 5 entries completely determine how this operates. Change these to whatever you want if
# different from the standard install.

OA4MP_ROOT=${OA4MP_HOME}
jwtJar=$OA4MP_ROOT/lib/jwt.jar

# End of user serviceable parts.

java -jar $jwtJar  "$@"

if [ $? != 0 ]; then
  exit 1
fi

exit 0
