#!/usr/bin/env bash
# Run the OA4MP CLI (command line interface). This will allow you to edit, create or remove
# clients, approvals. It will also allow you to copy one store to another completely.
# Invoke with --help for more information.
#
# The next 5 entries completely determine how this operates. Change these to whatever you want if
# different from the standard install.

OA4MP_ROOT=${OA4MP_HOME}
migrateJar=$OA4MP_ROOT/lib/fs-migrate.jar

# End of user serviceable parts.

if [[  "$1" = "--help" || $# -gt 2 ]];then
   java -jar $migrateJar --help
  exit 1
fi

java -jar "$migrateJar" "$@"

if [ $? != 0 ]; then
  exit 1
fi

exit 0
